### ISSUE TITLE
plugin wil not start

### ISSUE THREAD

**Issue by ghost** [CyR1en/Minecordbot#103]
What is supposed to happen?
ingame chat sendt to a discord tekst channel

What actually happens?
plugin does not start

What steps reproduce the problem?
starting the server it gives a error

------
What is your Minecordbot version?
2.2.5

What is your craftbukkit / spigot version?
1.12.2

[02:30:58] [Server thread/WARN]: [MineCordBot] Task #507 for MineCordBot v2.2.5 generated an exception
java.lang.NoSuchMethodError: net.dv8tion.jda.core.entities.Game.playing(Ljava/lang/String;)Lnet/dv8tion/jda/core/entities/Game;
	at com.jagrosh.jdautilities.commandclient.CommandClientBuilder.<init>(CommandClientBuilder.java:40) ~[?:?]
	at us.cyrien.minecordbot.Bot.<init>(Bot.java:86) ~[?:?]
	at us.cyrien.minecordbot.Minecordbot.lambda$start$0(Minecordbot.java:84) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-93e20b3-b8f84f3]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by TheIntelloBox** [comment]
Is this the full error ?
